name: Example GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 24f2006569@ds.study.iitm.ac.in
        run: echo "Hello, world!"
